# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1n7fSPVTA7BloIW4RYvj2bWJkOC3gpRD0
"""

print('Pilih salah satu')
print('1. Perhitungan bangun datar')
print('2. Perhitungan bangun ruang')
pilih1=int(input("Pilihan : "))
if (pilih1 == 1):
  print()
  print('Bangun datar yang akan dihitung')
  print('1. Persegi')
  print('2. Persegi Panjang')
  print('3. Segitiga')
  print('4. Trapesium')
  pilih2=int(input('Pilihan : '))
  print()
  if (pilih2 == 1):
    print('1. Luas Persegi')
    print('2. Keliling Persegi')
    pilpersegi=int(input('Pilihan : '))
    if (pilpersegi==1):
      x=int(input('Panjang sisi : '))
      def lpersegi(x):
         return x**2
      print ('Hasil : ', lpersegi(x))
    elif (pilpersegi==2):
      x=int(input('Panjang sisi : ')) 
      def kpersegi(x):
        return 4*x
      print ('Hasil : ', kpersegi(x))
  elif (pilih2 == 2):
    print('1. Luas Persegi Panjang')
    print('2. Keliling Persegi Panjang')
    pilperspanjang=int(input('Pilihan : '))
    print()
    if (pilperspanjang==1):
      x=int(input('Panjang : '))
      y=int(input('Lebar : '))
      def lppanjang(x,y):
        return x*y
      print ('Hasil : ', lppanjang(x,y))
    elif (pilperspanjang):
      x=int(input('Panjang : '))
      y=int(input('Lebar : '))
      def kppanjang(x,y):
        return 2*(x+y)
      print ('Hasil : ', kppanjang(x,y))

from browser import document, console, alert

input = document['input']
button = document['btn']
output = document['output']
select = document['select']

def getNum(x):
    temp = x
    try:
        temp = int(x)
    except ValueError:
        temp = float(x)
    finally:
        if temp != '' and type(temp) is str:
            alert('Harap masukkan angka')
            temp = ''
            input.value = temp
            return temp
        else:
            return temp

def formula(x, y):
    match x:
        case 'keliling persegi':
            return 4 * y
        case 'luas persegi':
            return y ** 3
        case _:        
            return 0

#Persegi Panjang
def perpanjang(x,y):
    match x,y:
        case 'Keliling Persegi Panjang':
            return 2*(x+y)
        case 'Luas Persegi Panjang'
            return x*y
        case _:        
            return 0

def main(ev):
    num = getNum(input.value)
    result = formula(select.value, num)
    output.textContent = str(result)

def keyEnter(ev):
    console.log(f"{ev.code}")
    traceKey = f"{ev.code}"
    if traceKey == 'Enter':
        main(0)

button.bind('click', main)
input.bind("keypress", keyEnter)